---
title: "PS270 Final Project"
author: "Wolfi Vetter"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...
how Democrats have consistently overperformed in off-year elections since Roe v. Wade was overturned.



Question: How do election results skew differently following the Supreme Court's decision to overturn Roe v. Wade? I believe that the election results have skewed more heavily towards the Democratic party following the termination of Roe. This is evident in abortion ballot initiatives, the 2022 Congressional midterms, and special elections occurring in 2023 and 2024, leading up to the 2024 presidential election. In order to properly conclude this idea, I will need to show polls and subsequent exit polls for the 2022 midterms and special elections, not only in districts that lean Republican but also districts that lean Democratic. Thankfully I already have a small list of examples from both sides of thi coin which I can use as a starting base. Additionally, I recall an MSNBC video where Chris Hayes explains how Democrats have overperformed consistently in 2023 special elections by an average of 8 points. If I can find that video, it should have a list of these elections and can further help my case.